#!/usr/bin/env zsh
case "$1" in
  init)
    echo "echo 'MOCKED: pyenv init'"
    ;;
  versions)
    echo "3.14.2-mock"
    ;;
  install)
    echo "MOCKED: pyenv install $*"
    ;;
  global)
    echo "MOCKED: pyenv global $*"
    ;;
  which)
    echo "python"
    ;;
  *)
    echo "pyenv 2.3.0-mock"
    ;;
esac
exit 0
